// DataStore. Org-scoped domain data lives in Supabase (issue #14). Identity comes from
// Supabase Auth (issue #18) — resolved in lib/auth.ts; this module only maps auth user
// ids to their organization via getOrgForUser.
// Server-side only: imported exclusively from RSC, actions, and route handlers.
//
// The Supabase client uses the service-role key and therefore bypasses RLS — every query
// here is additionally scoped by organization_id server-side (defense in depth, §II).
import crypto from "node:crypto";
import { cache } from "react";
import type {
  ConflictResolution,
  GenerationResult,
  ImportAnalysis,
  ImportedFileDigest,
  ImportSourceKind,
  ImportSourceStatus,
  InterviewAnswers,
  JobStage,
  JobStatus,
  ProjectModel
} from "@airrow/schemas";
import { db, rows, maybe, single } from "./supabase";

export type ProjectStatus = "interviewing" | "generating" | "ready" | "failed";

export interface UserRecord {
  id: string;
  email: string;
  name: string;
  createdAt: string;
}

/**
 * What an organization is entitled to (spec 74). Free is the default every org starts on; Pro is
 * written by migration or the billing webhook, never by the app on a member's behalf.
 */
export type OrgPlan = "free" | "pro";

export interface OrgRecord {
  id: string;
  name: string;
  kind: "personal" | "team";
  createdBy: string;
  plan: OrgPlan;
}

export interface MemberRecord {
  organizationId: string;
  userId: string;
  role: "owner" | "admin" | "member";
}

export interface ProjectRecord {
  id: string;
  organizationId: string;
  name: string;
  slug: string;
  description: string;
  status: ProjectStatus;
  createdAt: string;
  updatedAt: string;
}

export interface InterviewRecord {
  id: string;
  projectId: string;
  schemaVersion: string;
  answers: InterviewAnswers;
  completedAt: string | null;
}

export interface ModelVersionRecord {
  id: string;
  projectId: string;
  version: number;
  model: ProjectModel;
  createdAt: string;
}

export interface JobRecord {
  id: string;
  projectId: string;
  modelVersionId: string;
  status: JobStatus;
  stage: JobStage | null;
  stagesDone: JobStage[];
  filesAuthored: number;
  totalFiles: number;
  currentPath: string | null;
  error: string | null;
  heartbeatAt: string;
  startedAt: string | null;
  finishedAt: string | null;
}

export interface DeliveryRecord {
  id: string;
  projectId: string;
  jobId: string;
  method: "zip" | "github";
  status: "completed" | "failed";
  createdAt: string;
}

export const uid = (): string => crypto.randomUUID();
const now = (): string => new Date().toISOString();

/* ── Row shapes (snake_case) + mappers ────────────────────────────────────── */

interface OrgRow {
  id: string;
  name: string;
  kind: "personal" | "team";
  created_by: string | null;
  plan: string | null;
}
const toOrg = (r: OrgRow): OrgRecord => ({
  id: r.id,
  name: r.name,
  kind: r.kind,
  createdBy: r.created_by ?? "",
  // Anything that is not exactly 'pro' is free. The column is constrained and defaulted, so this
  // only ever fires on a row written before the migration — and defaulting an unknown value *down*
  // is the one safe direction for an entitlement.
  plan: r.plan === "pro" ? "pro" : "free"
});

interface ProjectRow {
  id: string;
  organization_id: string;
  name: string;
  slug: string;
  description: string;
  status: ProjectStatus;
  created_at: string;
  updated_at: string;
}
const toProject = (r: ProjectRow): ProjectRecord => ({
  id: r.id,
  organizationId: r.organization_id,
  name: r.name,
  slug: r.slug,
  description: r.description,
  status: r.status,
  createdAt: r.created_at,
  updatedAt: r.updated_at
});

interface InterviewRow {
  id: string;
  project_id: string;
  schema_version: string;
  answers: InterviewAnswers;
  completed_at: string | null;
}
const toInterview = (r: InterviewRow): InterviewRecord => ({
  id: r.id,
  projectId: r.project_id,
  schemaVersion: r.schema_version,
  answers: r.answers,
  completedAt: r.completed_at
});

interface ModelRow {
  id: string;
  project_id: string;
  version: number;
  /** As stored: rows written before `origin` existed (spec 91) have none. */
  model: Omit<ProjectModel, "origin"> & Partial<Pick<ProjectModel, "origin">>;
  created_at: string;
}
const toModel = (r: ModelRow): ModelVersionRecord => ({
  id: r.id,
  projectId: r.project_id,
  version: r.version,
  // Every model version written before `origin` existed was generated by the pipeline as it behaved
  // then: `/start`, unconditionally. Saying so is more honest than leaving the field undefined
  // behind a type that promises otherwise.
  model: { ...r.model, origin: r.model.origin ?? { kind: "new" } },
  createdAt: r.created_at
});

interface JobRow {
  id: string;
  project_id: string;
  model_version_id: string;
  status: JobStatus;
  stage: JobStage | null;
  stages_done: JobStage[];
  files_authored: number;
  total_files: number;
  current_path: string | null;
  error: string | null;
  heartbeat_at: string;
  started_at: string | null;
  finished_at: string | null;
}
const toJob = (r: JobRow): JobRecord => ({
  id: r.id,
  projectId: r.project_id,
  modelVersionId: r.model_version_id,
  status: r.status,
  stage: r.stage,
  stagesDone: r.stages_done,
  filesAuthored: r.files_authored,
  totalFiles: r.total_files,
  currentPath: r.current_path,
  error: r.error,
  heartbeatAt: r.heartbeat_at,
  startedAt: r.started_at,
  finishedAt: r.finished_at
});

/* ── Organization resolution (identity comes from Supabase Auth, in lib/auth.ts) ── */

/** The organization a user belongs to (their personal org). Null if none yet. */
export async function getOrgForUser(userId: string): Promise<OrgRecord | null> {
  const memberships = rows<{ organization_id: string }>(
    await db().from("organization_members").select("organization_id").eq("user_id", userId)
  );
  const orgId = memberships[0]?.organization_id;
  if (!orgId) return null;
  const org = maybe<OrgRow>(
    await db()
      .from("organizations")
      .select("id, name, kind, created_by, plan")
      .eq("id", orgId)
      .maybeSingle()
  );
  return org ? toOrg(org) : null;
}

/** Keep profiles.display_name in sync with the auth user's name. */
export async function setDisplayName(userId: string, name: string): Promise<void> {
  const res = await db().from("profiles").update({ display_name: name }).eq("id", userId);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/**
 * Undo a signup that should never have happened (spec 67).
 *
 * A GitHub identity whose e-mail address GitHub itself has not verified proves nothing about who is
 * signing in, so the spec's answer is that no account is created — but the account exists by the time
 * the callback can see the address, because `handle_new_user` fires on insert. This removes it: the
 * personal org and membership the trigger provisioned, then the auth user (which cascades the
 * profile). Nothing else is reachable yet — the account is seconds old and owns no projects.
 *
 * The one destructive call in the DataStore, and deliberately not a general "delete a user": the
 * caller must have established that this account is brand new and has a single unverified identity.
 */
export async function purgeUnverifiedSignup(userId: string): Promise<void> {
  const membership = await db().from("organization_members").delete().eq("user_id", userId);
  if (membership.error) throw new Error(`Supabase: ${membership.error.message}`);

  const orgs = await db()
    .from("organizations")
    .delete()
    .eq("created_by", userId)
    .eq("kind", "personal");
  if (orgs.error) throw new Error(`Supabase: ${orgs.error.message}`);

  const { error } = await db().auth.admin.deleteUser(userId);
  if (error) throw new Error(`Supabase: ${error.message}`);
}

/* ── Projects (always org-scoped) ─────────────────────────────────────────── */

/**
 * Memoised per request: the app shell and the dashboard each need the project list, and
 * without this a single `/app` render queried it twice. `cache()` is scoped to one
 * request, so a mutation followed by a fresh navigation still reads current data.
 */
export const listProjects = cache(async (orgId: string): Promise<ProjectRecord[]> => {
  const data = rows<ProjectRow>(
    await db()
      .from("projects")
      .select("*")
      .eq("organization_id", orgId)
      .order("updated_at", { ascending: false })
  );
  return data.map(toProject);
});

export async function getProject(orgId: string, projectId: string): Promise<ProjectRecord | null> {
  const row = maybe<ProjectRow>(
    await db().from("projects").select("*").eq("id", projectId).eq("organization_id", orgId).maybeSingle()
  );
  return row ? toProject(row) : null;
}

export async function createProject(
  orgId: string,
  name: string,
  description: string,
  slugify: (s: string) => string
): Promise<ProjectRecord> {
  const base = slugify(name);
  const taken = new Set(
    rows<{ slug: string }>(
      await db().from("projects").select("slug").eq("organization_id", orgId)
    ).map((r) => r.slug)
  );
  let slug = base;
  let n = 2;
  while (taken.has(slug)) slug = `${base}-${n++}`;

  const project = single<ProjectRow>(
    await db()
      .from("projects")
      .insert({ organization_id: orgId, name, slug, description, status: "interviewing" })
      .select("*")
      .single()
  );
  const interviewRes = await db()
    .from("interviews")
    .insert({ project_id: project.id, schema_version: "1", answers: {} });
  if (interviewRes.error) throw new Error(`Supabase: ${interviewRes.error.message}`);
  return toProject(project);
}

export async function setProjectStatus(projectId: string, status: ProjectStatus): Promise<void> {
  const res = await db()
    .from("projects")
    .update({ status, updated_at: now() })
    .eq("id", projectId);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/** Delete a project; interviews/models/jobs/artifacts/deliveries cascade via FK. */
export async function deleteProject(orgId: string, projectId: string): Promise<void> {
  const res = await db()
    .from("projects")
    .delete()
    .eq("id", projectId)
    .eq("organization_id", orgId);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/* ── Interviews ─────────────────────────────────────────────────────────── */

export async function getInterview(projectId: string): Promise<InterviewRecord | null> {
  const row = maybe<InterviewRow>(
    await db().from("interviews").select("*").eq("project_id", projectId).maybeSingle()
  );
  return row ? toInterview(row) : null;
}

export async function saveInterviewAnswers(
  projectId: string,
  answers: InterviewAnswers
): Promise<void> {
  const res = await db().from("interviews").update({ answers }).eq("project_id", projectId);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
  const touch = await db().from("projects").update({ updated_at: now() }).eq("id", projectId);
  if (touch.error) throw new Error(`Supabase: ${touch.error.message}`);
}

export async function completeInterview(projectId: string): Promise<void> {
  const res = await db()
    .from("interviews")
    .update({ completed_at: now() })
    .eq("project_id", projectId);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/* ── Model versions ─────────────────────────────────────────────────────── */

export async function createModelVersion(
  projectId: string,
  model: ProjectModel
): Promise<ModelVersionRecord> {
  const latest = await latestModelVersion(projectId);
  const version = (latest?.version ?? 0) + 1;
  const row = single<ModelRow>(
    await db()
      .from("project_models")
      .insert({ project_id: projectId, version, model })
      .select("*")
      .single()
  );
  return toModel(row);
}

export async function latestModelVersion(projectId: string): Promise<ModelVersionRecord | null> {
  const row = maybe<ModelRow>(
    await db()
      .from("project_models")
      .select("*")
      .eq("project_id", projectId)
      .order("version", { ascending: false })
      .limit(1)
      .maybeSingle()
  );
  return row ? toModel(row) : null;
}

/* ── Jobs ───────────────────────────────────────────────────────────────── */

export async function createJob(projectId: string, modelVersionId: string): Promise<JobRecord> {
  const row = single<JobRow>(
    await db()
      .from("generation_jobs")
      .insert({ project_id: projectId, model_version_id: modelVersionId, status: "queued" })
      .select("*")
      .single()
  );
  return toJob(row);
}

interface UsageRow {
  generation_job_id: string | null;
  created_at: string;
}

/**
 * Ledger rows an organization was actually charged for, scoped by whichever column the caller cares
 * about — the org (its whole allowance) or one project (its repairs).
 *
 * Two kinds of job are excluded, for the same reason: Airrow never paid for them. A `failed` job
 * fell over on our side, and a `reused_authoring` job answered from a previous run's payload without
 * calling Claude at all (spec 74). A row whose job is gone counts — it completed, was delivered, and
 * the project was then deleted.
 */
async function chargedUsage(column: "organization_id" | "project_id", id: string): Promise<UsageRow[]> {
  const usage = rows<UsageRow>(
    await db().from("generation_usage").select("generation_job_id, created_at").eq(column, id)
  );
  if (usage.length === 0) return [];

  const jobIds = usage.map((u) => u.generation_job_id).filter((v): v is string => v !== null);
  if (jobIds.length === 0) return usage;

  const jobs = rows<{ id: string; status: JobStatus; reused_authoring: boolean }>(
    await db().from("generation_jobs").select("id, status, reused_authoring").in("id", jobIds)
  );
  // Filtered here rather than in the query: two independent conditions expressed as a PostgREST
  // `or` string is the kind of thing that stays syntactically valid while meaning something else.
  const uncharged = new Set(
    jobs.filter((j) => j.status === "failed" || j.reused_authoring).map((j) => j.id)
  );
  return usage.filter((u) => u.generation_job_id === null || !uncharged.has(u.generation_job_id));
}

/**
 * Generations this organization has spent, from the durable ledger.
 *
 * This used to count live `generation_jobs`, which cascade away with their project — so deleting a
 * project refunded the allowance, and the ceiling could be reset at will. `generation_usage` rows
 * are written by a trigger and survive their project, because a Claude call is paid for whether or
 * not what it produced still exists.
 */
export async function countGenerations(orgId: string): Promise<number> {
  return (await chargedUsage("organization_id", orgId)).length;
}

/** What one project has spent, which is what the free repair window is measured against (spec 74). */
export interface ProjectUsage {
  /** Charged generations on this project. The first is the foundation; the rest are repairs. */
  count: number;
  /** When the first charged generation ran, or null if there has never been one. */
  firstAt: string | null;
}

export async function projectUsage(projectId: string): Promise<ProjectUsage> {
  const usage = await chargedUsage("project_id", projectId);
  // Sorted rather than assuming insertion order: the window opens at the *first* generation, and
  // reading that off an arbitrary row would silently move the deadline.
  const first = usage.map((u) => u.created_at).sort()[0];
  return { count: usage.length, firstAt: first ?? null };
}

/** True when this account bypasses the free allowance. Set by migration only — never from the app. */
export async function isAdminUser(userId: string): Promise<boolean> {
  const row = maybe<{ is_admin: boolean }>(
    await db().from("profiles").select("is_admin").eq("id", userId).maybeSingle()
  );
  return row?.is_admin === true;
}

export async function getJob(jobId: string): Promise<JobRecord | null> {
  const row = maybe<JobRow>(
    await db().from("generation_jobs").select("*").eq("id", jobId).maybeSingle()
  );
  return row ? toJob(row) : null;
}

/**
 * The project's most recently *created* job — which is what every caller means by "latest".
 *
 * Ordered on `created_at` because it is the only column that is both always set and never changed.
 * This used to order on `started_at desc nulls last`, which is null until a job runs: a freshly
 * queued job therefore sorted *behind* the completed one it was meant to replace, so regenerating
 * an existing project started nothing and hung on `generating`. `heartbeat_at` is no better — every
 * update bumps it, so it says when a job was last touched, not when it was queued.
 */
export async function latestJob(projectId: string): Promise<JobRecord | null> {
  const row = maybe<JobRow>(
    await db()
      .from("generation_jobs")
      .select("*")
      .eq("project_id", projectId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle()
  );
  return row ? toJob(row) : null;
}

/** Column mapping for a partial job update; heartbeat is always bumped (matches prior behavior). */
function jobPatchToRow(patch: Partial<JobRecord>): Record<string, unknown> {
  const row: Record<string, unknown> = { heartbeat_at: now() };
  if (patch.status !== undefined) row.status = patch.status;
  if (patch.stage !== undefined) row.stage = patch.stage;
  if (patch.stagesDone !== undefined) row.stages_done = patch.stagesDone;
  if (patch.filesAuthored !== undefined) row.files_authored = patch.filesAuthored;
  if (patch.totalFiles !== undefined) row.total_files = patch.totalFiles;
  if (patch.currentPath !== undefined) row.current_path = patch.currentPath;
  if (patch.error !== undefined) row.error = patch.error;
  if (patch.startedAt !== undefined) row.started_at = patch.startedAt;
  if (patch.finishedAt !== undefined) row.finished_at = patch.finishedAt;
  return row;
}

export async function updateJob(jobId: string, patch: Partial<JobRecord>): Promise<void> {
  const res = await db().from("generation_jobs").update(jobPatchToRow(patch)).eq("id", jobId);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/* ── Authoring provenance & memoisation ───────────────────────────────────── */

/** What produced a job's prose. Written once, when authoring succeeds. */
export interface AuthoringProvenance {
  inputsHash: string;
  promptVersion: string;
  authoringModel: string;
  /** The validated `{ slots, documents }` payload, kept so an unchanged rerun can reuse it. */
  authored: unknown;
  /**
   * Whether this payload came from a previous job rather than from Claude. Recorded because the
   * allowance charges for calls Airrow made, and a reused payload is not one (spec 74).
   */
  reused: boolean;
}

export async function saveAuthoringProvenance(
  jobId: string,
  provenance: AuthoringProvenance
): Promise<void> {
  const res = await db()
    .from("generation_jobs")
    .update({
      inputs_hash: provenance.inputsHash,
      prompt_version: provenance.promptVersion,
      authoring_model: provenance.authoringModel,
      authored: provenance.authored,
      reused_authoring: provenance.reused
    })
    .eq("id", jobId);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/**
 * Prose from a previous run of the same inputs, or null.
 *
 * Scoped to the project, matched on all three of hash, prompt version and model — change any one and
 * this misses, which is the safe direction. Only `completed` jobs qualify: a failed or in-flight job
 * may have written a partial payload, and serving that would be worse than paying for the call.
 */
export async function findAuthoredByInputs(
  projectId: string,
  inputsHash: string,
  promptVersion: string,
  authoringModel: string
): Promise<unknown | null> {
  const row = maybe<{ authored: unknown }>(
    await db()
      .from("generation_jobs")
      .select("authored")
      .eq("project_id", projectId)
      .eq("inputs_hash", inputsHash)
      .eq("prompt_version", promptVersion)
      .eq("authoring_model", authoringModel)
      .eq("status", "completed")
      .not("authored", "is", null)
      .order("finished_at", { ascending: false })
      .limit(1)
      .maybeSingle()
  );
  return row?.authored ?? null;
}

/* ── Artifacts (GenerationResult as jsonb; one per job) ───────────────────── */

export async function saveArtifact(jobId: string, result: GenerationResult): Promise<void> {
  const res = await db()
    .from("artifacts")
    .upsert({ generation_job_id: jobId, result }, { onConflict: "generation_job_id" });
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

export async function loadArtifact(jobId: string): Promise<GenerationResult | null> {
  const row = maybe<{ result: GenerationResult }>(
    await db().from("artifacts").select("result").eq("generation_job_id", jobId).maybeSingle()
  );
  return row ? row.result : null;
}

/**
 * Replace one file's content in a stored artifact (founder edits in the preview). The manifest entry
 * is re-stamped so byte counts stay true and the file is marked as founder-edited — regeneration
 * always produces a fresh artifact, so an edit never silently outlives the answers it came from.
 */
export async function updateArtifactFile(
  jobId: string,
  filePath: string,
  content: string
): Promise<boolean> {
  const artifact = await loadArtifact(jobId);
  if (!artifact) return false;
  const file = artifact.files.find((f) => f.path === filePath);
  const entry = artifact.manifest.files.find((f) => f.path === filePath);
  if (!file || !entry) return false;

  file.content = content;
  file.source = "authored";
  entry.source = "authored";
  entry.bytes = new TextEncoder().encode(content).length;
  await saveArtifact(jobId, artifact);
  return true;
}

/* ── Imports (spec 63) ────────────────────────────────────────────────────── */

export interface ImportSourceRecord {
  id: string;
  projectId: string;
  kind: ImportSourceKind;
  status: ImportSourceStatus;
  originalName: string;
  filesAnalyzed: number;
  filesIgnored: number;
  analysis: ImportAnalysis;
  /** Which pepper version the digests were hashed with; 0 = raw SHA-256 (spec 68). */
  digestVersion: number;
  createdAt: string;
}

interface ImportSourceRow {
  id: string;
  project_id: string;
  kind: ImportSourceKind;
  status: ImportSourceStatus;
  original_name: string;
  files_analyzed: number;
  files_ignored: number;
  /** As stored: rows written before `stackDetected` existed (spec 91) have no answer to it. */
  analysis: Omit<ImportAnalysis, "stackDetected"> & Partial<Pick<ImportAnalysis, "stackDetected">>;
  digest_version: number;
  created_at: string;
}
const toImportSource = (r: ImportSourceRow): ImportSourceRecord => ({
  id: r.id,
  projectId: r.project_id,
  kind: r.kind,
  status: r.status,
  originalName: r.original_name,
  filesAnalyzed: r.files_analyzed,
  filesIgnored: r.files_ignored,
  // An import written before the measurement existed defaults to "there was code": every one of
  // them was a real project archive, and calling an unmeasured one empty would hand its founder
  // `/start` — the one command that does not fit a repository which already has code.
  analysis: { ...r.analysis, stackDetected: r.analysis.stackDetected ?? true },
  digestVersion: r.digest_version,
  createdAt: r.created_at
});

/**
 * Record an import and the digest manifest of what it contained. Only paths, sizes and digests are
 * persisted — the imported content stays in the request that analyzed it (§II, customer IP).
 */
export async function createImportSource(
  projectId: string,
  kind: ImportSourceKind,
  originalName: string,
  analysis: ImportAnalysis,
  files: ImportedFileDigest[],
  digestVersion: number
): Promise<ImportSourceRecord> {
  const row = single<ImportSourceRow>(
    await db()
      .from("import_sources")
      .insert({
        project_id: projectId,
        kind,
        status: "analyzed",
        original_name: originalName,
        files_analyzed: analysis.filesAnalyzed,
        files_ignored: analysis.filesIgnored,
        analysis,
        digest_version: digestVersion
      })
      .select("*")
      .single()
  );
  if (files.length > 0) {
    const res = await db()
      .from("import_files")
      .insert(files.map((f) => ({ import_source_id: row.id, path: f.path, bytes: f.bytes, digest: f.digest })));
    if (res.error) throw new Error(`Supabase: ${res.error.message}`);
  }
  return toImportSource(row);
}

export async function getImportSource(projectId: string): Promise<ImportSourceRecord | null> {
  const row = maybe<ImportSourceRow>(
    await db()
      .from("import_sources")
      .select("*")
      .eq("project_id", projectId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle()
  );
  return row ? toImportSource(row) : null;
}

export async function listImportFiles(importSourceId: string): Promise<ImportedFileDigest[]> {
  return rows<{ path: string; bytes: number; digest: string }>(
    await db().from("import_files").select("path, bytes, digest").eq("import_source_id", importSourceId)
  );
}

/** Record one explicit decision. Absence of a row means the existing file stands. */
export async function saveConflictResolution(
  importSourceId: string,
  jobId: string,
  path: string,
  resolution: ConflictResolution
): Promise<void> {
  const res = await db()
    .from("import_conflicts")
    .upsert(
      { import_source_id: importSourceId, generation_job_id: jobId, path, resolution },
      { onConflict: "generation_job_id,path" }
    );
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/** Undo a decision: back to undecided, which is a delivery outcome of its own (spec 91). */
export async function clearConflictResolution(jobId: string, path: string): Promise<void> {
  const res = await db()
    .from("import_conflicts")
    .delete()
    .eq("generation_job_id", jobId)
    .eq("path", path);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

export async function listConflictResolutions(jobId: string): Promise<Map<string, ConflictResolution>> {
  const data = rows<{ path: string; resolution: ConflictResolution }>(
    await db().from("import_conflicts").select("path, resolution").eq("generation_job_id", jobId)
  );
  return new Map(data.map((r) => [r.path, r.resolution]));
}

/* ── Deliveries ─────────────────────────────────────────────────────────── */

export async function recordDelivery(
  projectId: string,
  jobId: string,
  method: "zip" | "github"
): Promise<void> {
  const res = await db()
    .from("deliveries")
    .insert({ project_id: projectId, job_id: jobId, method, status: "completed" });
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/* ── Billing (spec 99) ──────────────────────────────────────────────────── */

/**
 * Stripe's state for an organization. The entitlement itself is `organizations.plan` — this is the
 * record of *why* it holds the value it does, and what the founder sees in settings.
 */
export interface SubscriptionRecord {
  organizationId: string;
  customerId: string;
  subscriptionId: string | null;
  /** Stripe's own vocabulary, kept verbatim: 'active', 'past_due', 'canceled', … */
  status: string;
  currentPeriodEnd: string | null;
  cancelAtPeriodEnd: boolean;
}

interface SubscriptionRow {
  organization_id: string;
  provider_customer_id: string;
  provider_subscription_id: string | null;
  status: string;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
}

const toSubscription = (r: SubscriptionRow): SubscriptionRecord => ({
  organizationId: r.organization_id,
  customerId: r.provider_customer_id,
  subscriptionId: r.provider_subscription_id,
  status: r.status,
  currentPeriodEnd: r.current_period_end,
  cancelAtPeriodEnd: r.cancel_at_period_end
});

const SUBSCRIPTION_COLUMNS =
  "organization_id, provider_customer_id, provider_subscription_id, status, current_period_end, cancel_at_period_end";

export async function getSubscription(orgId: string): Promise<SubscriptionRecord | null> {
  const row = maybe<SubscriptionRow>(
    await db()
      .from("subscriptions")
      .select(SUBSCRIPTION_COLUMNS)
      .eq("organization_id", orgId)
      .maybeSingle()
  );
  return row ? toSubscription(row) : null;
}

/**
 * Record the Stripe customer created for an organization, before any payment exists.
 *
 * Written at checkout rather than at the webhook so a founder who abandons Checkout and comes back
 * reuses their customer instead of accumulating one per attempt. `status: 'incomplete'` is Stripe's
 * own word for exactly this state and entitles them to nothing.
 */
export async function linkStripeCustomer(orgId: string, customerId: string): Promise<void> {
  const res = await db()
    .from("subscriptions")
    .upsert(
      {
        organization_id: orgId,
        provider_customer_id: customerId,
        status: "incomplete",
        updated_at: now()
      },
      { onConflict: "organization_id", ignoreDuplicates: true }
    );
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}

/** The organization behind a Stripe customer id. How the webhook, which has no session, scopes. */
export async function orgForStripeCustomer(customerId: string): Promise<string | null> {
  const row = maybe<{ organization_id: string }>(
    await db()
      .from("subscriptions")
      .select("organization_id")
      .eq("provider_customer_id", customerId)
      .maybeSingle()
  );
  return row?.organization_id ?? null;
}

export interface SubscriptionState {
  customerId: string;
  subscriptionId: string | null;
  status: string;
  currentPeriodEnd: string | null;
  cancelAtPeriodEnd: boolean;
  /** What this status entitles the organization to. Decided by the caller; written here. */
  plan: OrgPlan;
}

/**
 * Apply a subscription change: the billing row and the entitlement, together.
 *
 * These are deliberately one function and not two. They are the same fact viewed twice, and any
 * caller that could write one without the other is a caller that can leave an organization paying
 * for a plan it does not have — or holding a plan it stopped paying for.
 *
 * That is an argument about callers, not about atomicity: the Supabase client cannot wrap two
 * statements in a transaction, so a failure between them still diverges. The billing row is written
 * first on purpose. It is the lookup `orgForStripeCustomer` needs, so a half-applied event leaves
 * enough behind for the redelivery to find the organization and finish the job — and the webhook
 * releases its claim on failure so that redelivery actually gets to run.
 *
 * This is the **only** path that writes `organizations.plan` outside a migration, which is what the
 * column-level revoke in `20260729120000_pro_plan.sql` is there to guarantee.
 */
export async function applySubscriptionState(
  orgId: string,
  state: SubscriptionState
): Promise<void> {
  const sub = await db().from("subscriptions").upsert(
    {
      organization_id: orgId,
      provider_customer_id: state.customerId,
      provider_subscription_id: state.subscriptionId,
      status: state.status,
      current_period_end: state.currentPeriodEnd,
      cancel_at_period_end: state.cancelAtPeriodEnd,
      updated_at: now()
    },
    { onConflict: "organization_id" }
  );
  if (sub.error) throw new Error(`Supabase: ${sub.error.message}`);

  const org = await db().from("organizations").update({ plan: state.plan }).eq("id", orgId);
  if (org.error) throw new Error(`Supabase: ${org.error.message}`);
}

/**
 * Claim a Stripe event id, returning false if it has already been applied.
 *
 * Stripe delivers at least once and retries for days on a non-2xx, so "have we seen this?" has to be
 * answered atomically or two concurrent redeliveries both pass the check. The primary key does that
 * for us: the insert either succeeds or violates the key, with no lock of ours involved.
 */
export async function claimStripeEvent(eventId: string, eventType: string): Promise<boolean> {
  const res = await db().from("stripe_events").insert({ event_id: eventId, event_type: eventType });
  if (!res.error) return true;
  // 23505 is unique_violation: seen before, which is a successful no-op rather than a failure.
  if (res.error.code === "23505") return false;
  throw new Error(`Supabase: ${res.error.message}`);
}

/**
 * Give a claimed event back, because applying it failed.
 *
 * Without this the claim is a trap: Stripe retries a 500, the retry finds the id already recorded,
 * answers "duplicate", and an upgrade a founder paid for is lost permanently and silently. The claim
 * is there to stop two *concurrent* deliveries doing the same work — it must not also stop the
 * redelivery that exists precisely because the work did not happen.
 */
export async function releaseStripeEvent(eventId: string): Promise<void> {
  const res = await db().from("stripe_events").delete().eq("event_id", eventId);
  if (res.error) throw new Error(`Supabase: ${res.error.message}`);
}
