// Repo entry points + AI context system. Every document interpolates model facts
// (Constitution §2: never generic).

import type { GeneratedFile, ProjectModel } from "../../../schemas/src/types.ts";
import {
  audienceLabel,
  backendSummary,
  databaseLabel,
  featureLabel,
  featureList,
  frameworkLabel,
  hostingLabel,
  isSpaFramework,
  productTypeLabel,
  repoLabel,
  teamLabel,
  usesSupabase
} from "../model.ts";

const authored = (path: string, templateId: string, content: string): GeneratedFile => ({
  path,
  templateId,
  source: "authored",
  content: content.trimStart()
});

export function readme(m: ProjectModel): GeneratedFile {
  return authored(
    "README.md",
    "core/readme",
    `
# ${m.name}

${m.description}

A ${productTypeLabel[m.productType]} for ${audienceLabel[m.audience]}, built by ${teamLabel[m.team]} with AI-assisted development.

> **This repository was generated by [Airrow](https://airrow.dev).** It contains the complete engineering foundation — architecture, specifications, standards, and AI context — for building ${m.name} with ${frameworkLabel(m)}, ${databaseLabel(m)}, and Claude Code. No application code exists yet; that's the point. Read on.

## Start here

1. **[START_HERE.md](START_HERE.md)** — your guided first hour
2. **[docs/GETTING_STARTED.md](docs/GETTING_STARTED.md)** — environment setup
3. **[context/PROGRESS.md](context/PROGRESS.md)** — current state and next actions

AI assistants: your entry point is **[CLAUDE.md](CLAUDE.md)**.

## Stack

${frameworkLabel(m)} · TypeScript (strict) · Tailwind CSS · shadcn/ui · ${backendSummary(m)} · ${hostingLabel[m.hosting]} · ${repoLabel(m)} · VS Code + Claude Code

## Planned capabilities

${m.features.map((f) => `- ${featureLabel[f]}`).join("\n")}

## Repository map

| Path | Contents |
|------|----------|
| \`context/\` | AI context: state, constraints, decisions — read first |
| \`specs/\` | Feature specifications — the source of truth |
| \`docs/\` | Vision, roadmap, architecture, standards, guides |
| \`adr/\` | Architecture decision records |
| \`prompts/\` | Prompt library for AI-assisted development |
| \`templates/\` | Spec/ADR/PR templates |
| \`checklists/\` | Feature workflow checklist |

## The rule that matters most

**No spec, no code.** Every feature starts from a specification in \`specs/\`. See \`docs/workflows/FEATURE_WORKFLOW.md\`.
`
  );
}

export function startHere(m: ProjectModel): GeneratedFile {
  const mvp = m.mvpFocus || m.description;
  return authored(
    "START_HERE.md",
    "core/start-here",
    `
# START HERE — ${m.name}

Welcome. This repository is your engineering foundation: everything a senior CTO would put in place *before* writing code. Spend one hour here and you'll build faster for months.

## Why this exists

AI coding assistants are only as good as the context they're given. This repo gives Claude Code (or any assistant) your business goals, architecture, standards, and current progress — so generated code is consistent, correct, and yours.

## Your first hour

**1. Understand your own plan (20 min)**

- \`docs/VISION.md\` — ${m.name} in one page
- \`docs/ROADMAP.md\` — your milestones. MVP focus: *"${mvp}"*
- \`docs/architecture/ARCHITECTURE.md\` — how the system fits together

**2. Learn the workflow (20 min)**

- \`docs/workflows/FEATURE_WORKFLOW.md\` — the loop you'll repeat for every feature
- \`specs/README.md\` — why specs come first, always
- \`checklists/FEATURE_CHECKLIST.md\` — print this, follow it every time

**3. Set up and start (20 min)**

- \`docs/GETTING_STARTED.md\` — install tools, create Supabase project, run locally
- Open this folder in VS Code, start Claude Code, and paste the first prompt from \`prompts/PROMPT_LIBRARY.md\` ("Kickoff").

## The working rhythm

1. Pick the top item in \`docs/ROADMAP.md\`.
2. Write its spec from \`templates/SPEC_TEMPLATE.md\` (Claude drafts, you decide).
3. Implement with Claude Code against the spec.
4. Review against the spec. Update docs + \`context/PROGRESS.md\`.
5. Commit, merge, repeat.

${m.team === "solo" ? "You're solo — the process still pays off. It's what keeps your AI assistant consistent when you return after three days away." : "Your whole team follows the same loop — that consistency is what keeps a shared AI-assisted codebase coherent."}

**Never skip the spec.** It's the difference between directing AI and gambling with it.
`
  );
}

export function claudeMd(m: ProjectModel): GeneratedFile {
  return authored(
    "CLAUDE.md",
    "core/claude-md",
    `
# CLAUDE.md — AI Assistant Context for ${m.name}

You are working on **${m.name}**: ${m.description} A ${productTypeLabel[m.productType]} for ${audienceLabel[m.audience]}.

**What we're building toward:** ${m.vision || "[NEEDS CLARIFICATION: long-term vision]"} Keep this destination in mind — every feature should move ${m.name} closer to it.

## Read before any work

1. \`context/PROGRESS.md\` — current state, what to work on next
2. \`context/CONSTRAINTS.md\` — hard rules you must never break
3. The spec for the current feature in \`specs/\`

## Deeper context (read as needed)

- \`context/PROJECT.md\` — business context
- \`context/ARCHITECTURE.md\` — condensed architecture (full: \`docs/architecture/\`)
- \`context/DECISIONS.md\` — decisions already made; don't relitigate
- \`docs/standards/\` — coding, testing, security, git standards

## Non-negotiable workflow

1. **No spec, no code.** Draft the spec first (\`templates/SPEC_TEMPLATE.md\`) if it doesn't exist.
2. If implementation must diverge from the spec, update the spec first.
3. Follow \`checklists/FEATURE_CHECKLIST.md\` top to bottom.
4. Update \`context/PROGRESS.md\` and affected docs in the same change as the work.
5. Significant technical decisions → new ADR in \`adr/\`.

## Stack

${frameworkLabel(m)} + TypeScript strict + Tailwind + shadcn/ui · ${backendSummary(m)} · ${hostingLabel[m.hosting]} · ${repoLabel(m)}

## Key rules (full list in context/CONSTRAINTS.md)

- TypeScript strict; no \`any\`. Zod validation at every boundary.
${isSpaFramework(m) ? "- Keep the SPA thin; business logic in typed modules, not components." : "- Server Components by default; Server Actions for mutations."}
- Every table has Row Level Security${m.derived.multiTenant ? ", scoped through organization membership" : ""}.
- Secrets only in environment variables — never in code${m.security === "elevated" ? ". Elevated data sensitivity: see docs/standards/SECURITY_STANDARDS.md before touching user data" : ""}.
`
  );
}

export function contextFiles(m: ProjectModel): GeneratedFile[] {
  const project = authored(
    "context/PROJECT.md",
    "context/project",
    `
# Project Context — ${m.name}

**Product:** ${m.description}

**Vision:** ${m.vision || "[NEEDS CLARIFICATION: long-term vision]"}

**Type:** ${productTypeLabel[m.productType]} · **Audience:** ${audienceLabel[m.audience]} · **Team:** ${teamLabel[m.team]}

**MVP focus:** ${m.mvpFocus}

**Planned capabilities:** ${featureList(m)}.

**Positioning note:** everything in this repo serves the MVP focus above. When prioritization is unclear, choose the option that ships the MVP focus sooner.
`
  );

  const architecture = authored(
    "context/ARCHITECTURE.md",
    "context/architecture",
    `
# Architecture Context (condensed)

Full details: \`docs/architecture/\`.

- **Frontend:** ${frameworkLabel(m)}, TypeScript strict, Tailwind, shadcn/ui.${isSpaFramework(m) ? "" : " Server Components default; client components only for interactivity."}
- **Backend:** ${usesSupabase(m) ? `Supabase — PostgreSQL with RLS on every table${m.derived.needsAuth ? ", Supabase Auth" : ""}${m.features.includes("storage") ? ", Storage for uploads" : ""}${m.derived.hasRealtime ? ", Realtime channels" : ""}` : `${databaseLabel(m)} — PostgreSQL with RLS on every table${m.derived.needsAuth || m.features.includes("storage") || m.derived.hasRealtime ? "; wire Auth/Storage/Realtime separately (Supabase is the golden path)" : ""}`}.
- **Tenancy:** ${m.derived.multiTenant ? `multi-tenant — every domain table carries \`organization_id\`; RLS scopes through membership. Roles: ${m.roles}.` : "single-tenant per user — rows scoped by `user_id` via RLS."}
${m.derived.hasPayments ? `- **Payments:** Stripe ${m.audience === "b2c" ? "(consumer checkout)" : "(subscription billing)"} — webhooks are the source of truth for entitlements.` : ""}
${m.derived.hasAi ? "- **AI:** LLM calls server-side only; prompts versioned in `prompts/`; outputs validated before use." : ""}
- **Deploy:** ${hostingLabel[m.hosting]}${m.hosting === "vercel" ? " (preview per PR, production from main)" : " (adjust the generated deploy workflow, which defaults to Vercel)"}. Code on ${repoLabel(m)}.

**Invariants:** typed data layer (no ad-hoc queries in components) · Zod at boundaries · migrations are the only schema change path.
`
  );

  const progress = authored(
    "context/PROGRESS.md",
    "context/progress",
    `
# Progress

> Update this file in the same change as any state-changing work. Your AI assistant reads it first, every session.

## Current state

Foundation generated by Airrow on ${new Date().toISOString().slice(0, 10)}. **No application code yet.**

## Next up (in order)

1. Complete \`docs/GETTING_STARTED.md\` setup (tools, Supabase project, ${repoLabel(m)} repo)
2. Write the spec for the first roadmap feature (see \`docs/ROADMAP.md\`, Milestone 1)
3. Implement it following \`checklists/FEATURE_CHECKLIST.md\`

## Completed

- Engineering foundation generated (architecture, specs system, standards, AI context)

## Open questions / blockers

- None yet. Record them here as they appear — your AI assistant should know about blockers.
`
  );

  const decisions = authored(
    "context/DECISIONS.md",
    "context/decisions",
    `
# Decisions (summaries)

Full records in \`adr/\`. Don't relitigate these without a superseding ADR.

- **ADR-0001 — Stack:** ${frameworkLabel(m)} + TypeScript + Tailwind + shadcn/ui, ${databaseLabel(m)} backend, ${hostingLabel[m.hosting]} deployment, ${repoLabel(m)} for code${m.derived.hasPayments ? ", Stripe for payments" : ""}. Chosen for AI-assistant fluency, managed operations, and speed for ${teamLabel[m.team]}.
- **Tenancy:** ${m.derived.multiTenant ? `multi-tenant with organizations and ${m.roles} roles from day one — retrofitting tenancy is a rewrite.` : "user-scoped single tenancy — organizations can be added later behind the same RLS pattern."}
- **Methodology:** Specification Driven Development. Specs before code, always.
`
  );

  const constraints = authored(
    "context/CONSTRAINTS.md",
    "context/constraints",
    `
# Constraints — hard rules, never break

## Process

1. No feature implementation without a spec in \`specs/\`.
2. Spec diverging from reality → fix the spec first.
3. \`context/PROGRESS.md\` updates in the same change as the work.
4. Significant decisions → ADR; never silently contradict an ADR.

## Code

5. TypeScript strict; \`any\` forbidden.
6. Zod validation at every boundary (forms, API, webhooks${m.derived.hasAi ? ", LLM output" : ""}).
7. All data access through the typed data layer — no ad-hoc queries in UI.
8. Every table has RLS ${m.derived.multiTenant ? "scoped through organization membership" : "scoped to the owning user"}; write denial tests.

## Security

9. Secrets only in env vars. Never in code, client bundles, or logs.
${m.security === "elevated" ? "10. Elevated sensitivity: no user data in logs; encrypt exports; review docs/standards/SECURITY_STANDARDS.md before any feature touching personal data." : "10. No personal data in logs beyond IDs."}
${m.derived.hasPayments ? "11. Payment state changes only via verified Stripe webhooks — never trust client-side success callbacks." : ""}
`
  );

  return [project, architecture, progress, decisions, constraints];
}
