-- Invite a friend, get a week of Pro (spec 122).
--
-- The reward is Pro, but it must not be written to `organizations.plan`. That column means "this is
-- what Stripe told us" — `20260729120000_pro_plan.sql` revoked the write from `authenticated` to keep
-- it that way, and specs 99/100 narrowed the writers to one function. A referral week written there
-- would make an expired thank-you indistinguishable from a cancelled subscription, and would put a
-- second author on the one column that is supposed to have exactly one.
--
-- So the week lives in its own table and the entitlement is resolved as "Stripe's plan **or** an
-- active grant", server-side. Everything here is keyed by organization_id like every other resource
-- (§II): the personal workspace is what an entitlement lands on.
--
-- Idempotent, replays cleanly from zero.

/* ── The link ───────────────────────────────────────────────────────────────
 *
 * One code per organization, created on demand and never rotated: a founder who has already pasted
 * their link into a message must not find it dead a week later. The code is generated by the app
 * from `crypto.randomUUID()` — unguessable, and the unique index is what makes a collision a failed
 * insert rather than a stolen referral.
 */
create table if not exists public.referral_codes (
  organization_id uuid primary key references public.organizations(id) on delete cascade,
  code            text not null unique,
  created_at      timestamptz not null default now()
);

comment on table public.referral_codes is
  'One invite code per organization (spec 122). Stable for the lifetime of the workspace — links already sent keep working.';

/* ── Who invited whom ───────────────────────────────────────────────────────
 *
 * `referred_organization_id` is unique, and that constraint is the whole idempotence story: a link
 * clicked five times, or a confirmation route that runs twice, cannot produce two referrals for one
 * new workspace. A check that reads first and inserts second would race with itself.
 *
 * `matured_at` is set when the invited founder's first generation lands. `plan_grant_id` stays null
 * when that happens after the inviter has already earned their three — the referral is recorded as
 * matured-but-uncredited rather than silently dropped, so the cap can be audited instead of inferred.
 */
create table if not exists public.referrals (
  id                        uuid primary key default gen_random_uuid(),
  referrer_organization_id  uuid not null references public.organizations(id) on delete cascade,
  referred_organization_id  uuid not null unique references public.organizations(id) on delete cascade,
  attached_at               timestamptz not null default now(),
  matured_at                timestamptz,
  plan_grant_id             uuid,
  constraint referrals_not_self check (referrer_organization_id <> referred_organization_id)
);

create index if not exists referrals_referrer_idx
  on public.referrals (referrer_organization_id);

comment on table public.referrals is
  'An invited workspace and who invited it (spec 122). matured_at is set on the invited founder''s first generation; plan_grant_id is null when the inviter was already at the cap.';

/* ── The week itself ────────────────────────────────────────────────────────
 *
 * A grant is created queued: `starts_at` and `expires_at` are null until something asks for an
 * entitlement the organization does not otherwise have. That is what lets a week wait behind a paid
 * subscription without anyone predicting when the subscription ends — and why there is no "usable
 * until" column. An earned week does not expire before it has begun.
 */
create table if not exists public.plan_grants (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  source          text not null default 'referral',
  duration_days   integer not null,
  starts_at       timestamptz,
  expires_at      timestamptz,
  created_at      timestamptz not null default now(),
  constraint plan_grants_source_check check (source in ('referral')),
  -- Both or neither. A row with a start and no end would be Pro forever.
  constraint plan_grants_window_check check ((starts_at is null) = (expires_at is null))
);

create index if not exists plan_grants_org_idx
  on public.plan_grants (organization_id, expires_at);

comment on table public.plan_grants is
  'Pro earned rather than bought (spec 122). Never a substitute for organizations.plan, which stays Stripe''s alone — the entitlement is resolved as the plan OR an active grant.';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'referrals_plan_grant_fk'
  ) then
    alter table public.referrals
      add constraint referrals_plan_grant_fk
      foreign key (plan_grant_id) references public.plan_grants(id) on delete set null;
  end if;
end;
$$;

/* ── Access ─────────────────────────────────────────────────────────────────
 *
 * Readable by members of the organization the row is about, exactly like every other org-scoped
 * table. Writable by nobody but `service_role`.
 *
 * That asymmetry is the point, and it is stricter than the tables around it. `generation_usage` hands
 * `authenticated` the full set of DML because its rows are bookkeeping about work already done; these
 * rows *are* the entitlement. A founder who can insert into `plan_grants` has granted themselves Pro
 * from a browser console, and no RLS policy phrased as "your own organization" would stop them —
 * their own organization is precisely the one they would grant it to. So the privilege is never
 * given, and the denial test says so.
 */
alter table public.referral_codes enable row level security;
alter table public.referrals enable row level security;
alter table public.plan_grants enable row level security;

drop policy if exists "org members read referral_codes" on public.referral_codes;
create policy "org members read referral_codes" on public.referral_codes
  for select using (public.is_org_member(organization_id));

-- The inviter's view. The invited workspace deliberately cannot read the row: who recommended Airrow
-- to whom is the inviter's business, and the invited founder is never told they were a reward.
drop policy if exists "referrer reads referrals" on public.referrals;
create policy "referrer reads referrals" on public.referrals
  for select using (public.is_org_member(referrer_organization_id));

drop policy if exists "org members read plan_grants" on public.plan_grants;
create policy "org members read plan_grants" on public.plan_grants
  for select using (public.is_org_member(organization_id));

grant all on public.referral_codes to service_role;
grant all on public.referrals to service_role;
grant all on public.plan_grants to service_role;

grant select on public.referral_codes to authenticated;
grant select on public.referrals to authenticated;
grant select on public.plan_grants to authenticated;
